apiVersion: v1
kind: LimitRange
metadata:
  name: team-a-limits
  namespace: # TODO: namespace objetivo
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: # TODO: request CPU por defecto
        memory: # TODO: request memoria por defecto
      default:
        cpu: # TODO: límite CPU por defecto
        memory: # TODO: límite memoria por defecto
