apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2026-06-09T13:45:02Z"
  labels:
    beta.kubernetes.io/arch: arm64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: arm64
    kubernetes.io/hostname: kind-worker
    kubernetes.io/os: linux
    bla: bla
  name: kind-worker
  resourceVersion: "38655"
  uid: 60c45d3c-1165-4963-bbb9-c26562dd7232
spec:
  podCIDR: 10.244.2.0/24
  podCIDRs:
  - 10.244.2.0/24
  providerID: kind://docker/kind/kind-worker
status:
  addresses:
  - address: 172.19.0.3
    type: InternalIP
  - address: kind-worker
    type: Hostname
  allocatable:
    cpu: "14"
    ephemeral-storage: 474885720Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    hugepages-32Mi: "0"
    hugepages-64Ki: "0"
    memory: 8126124Ki
    pods: "110"
  capacity:
    cpu: "14"
    ephemeral-storage: 474885720Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    hugepages-32Mi: "0"
    hugepages-64Ki: "0"
    memory: 8126124Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2026-06-09T20:42:27Z"
    lastTransitionTime: "2026-06-09T13:45:02Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2026-06-09T20:42:27Z"
    lastTransitionTime: "2026-06-09T13:45:02Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2026-06-09T20:42:27Z"
    lastTransitionTime: "2026-06-09T13:45:02Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2026-06-09T20:42:27Z"
    lastTransitionTime: "2026-06-09T13:45:13Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  declaredFeatures:
  - ExtendWebSocketsToKubelet
  - InPlacePodLevelResourcesVerticalScaling
  - InPlacePodVerticalScalingInitContainers
  - RestartAllContainersOnContainerExits
  features:
    supplementalGroupsPolicy: true
  images:
  - names:
    - registry.k8s.io/ingress-nginx/controller@sha256:594ceea76b01c592858f803f9ff4d2cb40542cae2060410b2c95f75907d659e1
    sizeBytes: 110337337
  - names:
    - docker.io/library/import-2026-06-02@sha256:e323e9cc96bda6e0b3d49bc2558a6d4af30273a256e18fe69c970f549ca18192
    - registry.k8s.io/kube-apiserver-arm64:v1.36.1
    - registry.k8s.io/kube-apiserver:v1.36.1
    sizeBytes: 89920756
  - names:
    - docker.io/library/import-2026-06-02@sha256:83e4c9a1483100194e929e8075ed88e1634b784538579805b81f61bef00cc6ae
    - registry.k8s.io/kube-proxy-arm64:v1.36.1
    - registry.k8s.io/kube-proxy:v1.36.1
    sizeBytes: 80900326
  - names:
    - docker.io/library/import-2026-06-02@sha256:ebf066f959e8e672ecbe20fbc4d48c8e0534b1c4074c7b7c840189e96984c9ba
    - registry.k8s.io/kube-controller-manager-arm64:v1.36.1
    - registry.k8s.io/kube-controller-manager:v1.36.1
    sizeBytes: 80156772
  - names:
    - ghcr.io/headlamp-k8s/headlamp@sha256:899d106eeb55b0afc4ee6e51c03bc4418de0bd0e79c39744d4d0d751aae6a971
    - ghcr.io/headlamp-k8s/headlamp:v0.25.0
    sizeBytes: 74001055
  - names:
    - docker.io/library/import-2026-06-02@sha256:611443e0c4043c8aed8ce2284f7058830427df365a336718d070238dcb5ddd74
    - registry.k8s.io/kube-scheduler-arm64:v1.36.1
    - registry.k8s.io/kube-scheduler:v1.36.1
    sizeBytes: 57349853
  - names:
    - docker.io/kindest/kindnetd:v20260528-9350166c
    sizeBytes: 35645853
  - names:
    - registry.k8s.io/ingress-nginx/kube-webhook-certgen@sha256:01038e7de14b78d702d2849c3aad72fd25903c4765af63cf16aa3398f5d5f2dd
    sizeBytes: 24313259
  - names:
    - registry.k8s.io/etcd:3.6.8-0
    sizeBytes: 21145439
  - names:
    - registry.k8s.io/coredns/coredns:v1.14.2
    sizeBytes: 20766250
  - names:
    - docker.io/library/nginx@sha256:516475cc129da42866742567714ddc681e5eed7b9ee0b9e9c015e464b4221a00
    - docker.io/library/nginx:1.25-alpine
    sizeBytes: 20193659
  - names:
    - docker.io/kindest/local-path-provisioner:v20260521-9fb22683
    sizeBytes: 14213900
  - names:
    - docker.io/kindest/local-path-helper:v20260131-7181c60a
    sizeBytes: 2740462
  - names:
    - registry.k8s.io/pause:3.10
    sizeBytes: 267933
  nodeInfo:
    architecture: arm64
    bootID: 47ba55cc-c989-4142-9cab-196a9e0babe8
    containerRuntimeVersion: containerd://2.3.1
    kernelVersion: 6.12.76-linuxkit
    kubeProxyVersion: ""
    kubeletVersion: v1.36.1
    machineID: a941bb1767d248898e2dbd41fac2d1cf
    operatingSystem: linux
    osImage: Debian GNU/Linux 13 (trixie)
    swap:
      capacity: 1073737728
    systemUUID: a941bb1767d248898e2dbd41fac2d1cf
  runtimeHandlers:
  - features:
      recursiveReadOnlyMounts: true
      userNamespaces: true
    name: ""
  - features:
      recursiveReadOnlyMounts: true
      userNamespaces: true
    name: runc
  - features:
      recursiveReadOnlyMounts: true
      userNamespaces: true
    name: test-handler
