apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-cuota-basica
  namespace: dev
  labels:
    module: modulo-06
    exercise: guiado
    environment: dev
spec:
  hard:
    pods: "2"
    requests.cpu: "300m"
    requests.memory: 192Mi
    limits.cpu: "600m"
    limits.memory: 384Mi
