apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voyager-ingress
  namespace: voyager
  labels:
    app: voyager
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: voyager.local
      http:
        paths:
          - path: /voyager
            pathType: Prefix
            backend:
              service:
                name: frontend-svcß
                port:
                  number: 8080
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: 5000