# Pod que solo se ejecutará en nodos con label disk=ssd
apiVersion: v1
kind: Pod
metadata:
  name: nginx-ssd
  labels:
    app: nginx
    storage: high-performance
spec:
  nodeSelector:
    disk: ssd
  containers:
    - name: nginx
      image: nginx:1.25-alpine
      ports:
        - containerPort: 80
