# Pod con nodeSelector imposible — quedará en Pending
apiVersion: v1
kind: Pod
metadata:
  name: nginx-nvme
  labels:
    app: nginx
    storage: ultra-performance
spec:
  nodeSelector:
    gpu: "true"    # No existe ningún nodo con esta label
  containers:
    - name: nginx
      image: nginx:1.25-alpine
      ports:
        - containerPort: 80
