apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventario-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventario-db
  serviceName: db-headless
  template:
    metadata:
      labels:
        app: inventario-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: inventario
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: training123
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
