apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  namespace: app
spec:
  replicas: 3 # TODO: define 3 réplicas
  selector:
    matchLabels:
      app: nginx-app # TODO: completa el label del selector
  template:
    metadata:
      labels:
        app: nginx-app # TODO: usa el mismo label que en el selector
    spec:
      containers:
        - name: nginx
          image: docker.io/nginx:1.25
          ports:
            - containerPort: 80
