apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    module: modulo-07
    exercise: guiado
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/modulo-07/mysql
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: modulo-07-guiado
  labels:
    module: modulo-07
    exercise: guiado
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
