apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-uploads
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-uploads
  template:
    metadata:
      labels:
        app: webapp-uploads
    spec:
      containers:
        - name: web
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            # TODO: montar el volumen "uploads-storage" en /usr/share/nginx/html/uploads
      volumes:
        # TODO: conectar "uploads-storage" con el PVC uploads-pvc
