apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
spec:
  capacity:
    storage: # TODO: definir la capacidad
  accessModes:
    # TODO: agregar el modo de acceso correcto
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: # TODO: usar /data/webapp-uploads
