apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1 # TODO: usar el número correcto de réplicas
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: node:18 # TODO: usar la imagen correcta del compose
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: localhost # TODO: usar el nombre del Service de la base de datos
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: cambiarme # TODO: copiar el valor correcto
            - name: DB_USER
              value: cambiarme # TODO: copiar el valor correcto
            - name: DB_PASSWORD
              value: cambiarme # TODO: copiar el valor correcto
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort # TODO: este servicio debe ser interno
