apiVersion: v1
kind: Service
metadata:
  name: svc-rs-demo
  labels:
    app: rs-demo
    curso: kubernetes
spec:
  type: ClusterIP
  selector:
    app: rs-demo
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
